### ISSUE TITLE
Want to add a user.json file

### ISSUE THREAD

**Issue by SANJAY-NT** [keshavsingh3197/HacktoberFest-2021#14]
Want to add a username.json file as my 1st commit to the fest 21.

**Comment by keshavsingh3197** [comment]
i have merged your PR, you can suggest some more non-tech folder that can be used in future by anyone.

**Comment by shubhamhere** [comment]
Can i add a username.json file as my 1st commit to the fest 21

**Comment by keshavsingh3197** [comment]
> Can i add a username.json file as my 1st commit to the fest 21

your file name should be **shubhamhere.json**
yes you can add.

**Comment by soil-droid** [comment]
hello, my pr #76 has been approved and closed , would be great if you tag it with "hacktoberfest-accepted"
thank you

**Comment by IshaanGaba97** [comment]
My PR is merged but can you please add "hacktoberfest-accepted" in #23 **pull request**
Thanks!!

**Comment by keshavsingh3197** [comment]
if pr is merged then it will aslo be valid pr for getting swags or tshirts.

**Comment by shlokjjw** [comment]
Please merge my PR #153 
Thanking You,
Shlok Jhunjhunwala
